name: Deploy Admin Web

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.JCLOUD_SSH_HOST }}
          username: ${{ secrets.JCLOUD_SSH_USER }}
          key: ${{ secrets.JCLOUD_SSH_KEY }}
          port: ${{ secrets.JCLOUD_SSH_PORT }}
          script: |
            set -e
              cd /home/ubuntu/admin
              git fetch origin main
              git reset --hard origin/main
              
              if docker compose build --no-cache admin-front; then
                docker compose up -d --force-recreate admin-front
                docker image prune -f
            else
                exit 1
            fi
